import Head   from 'next/head'
import React  from 'react'

// ====================================
// ヘッダー情報
// ====================================
type Props = { title?: string }

export const HeadInfo: React.FC<Props> = ({ title = "べんちゃん" }) => {
  return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}
